# Generated by Django 4.1.5 on 2023-02-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0003_alter_price_age_alter_price_breed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="age",
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name="price",
            name="breed",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="price",
            name="color",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="price",
            name="temperament",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
