# Generated by Django 4.1.5 on 2023-02-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0015_resume"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Resume",
            new_name="Resue",
        ),
    ]
