# Generated by Django 4.1.5 on 2023-02-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0016_rename_resume_resue"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Resue",
            new_name="Resume",
        ),
    ]
