# Generated by Django 4.1.5 on 2023-02-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0020_rename_imge_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="title",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="email",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="name",
        ),
    ]
