# Generated by Django 4.1.5 on 2023-02-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0021_remove_image_title_remove_resume_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.CharField(default="1", max_length=255),
            preserve_default=False,
        ),
    ]
