# Generated by Django 4.1.5 on 2023-02-12 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0023_breed_remove_price_temperament_alter_price_breed"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="resume",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Cats.resume"
            ),
            preserve_default=False,
        ),
    ]
