# Generated by Django 4.1.5 on 2023-02-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0027_price_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="title",
        ),
    ]
