# Generated by Django 4.1.5 on 2023-02-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0029_price_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="image",
        ),
    ]
