# Generated by Django 4.1.5 on 2023-02-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0030_remove_price_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="image",
            field=models.ImageField(max_length=255, null=True, upload_to="images/"),
        ),
    ]
