# Generated by Django 4.1.5 on 2023-02-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0037_rename_imag_price_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="file",
            field=models.FileField(null=True, upload_to="Cats"),
        ),
    ]
