# Generated by Django 4.1.5 on 2023-02-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0044_image_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="owner",
        ),
        migrations.AddField(
            model_name="price",
            name="image",
            field=models.ImageField(max_length=255, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="price",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
