# Generated by Django 4.1.5 on 2023-02-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0046_price_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="title",
        ),
        migrations.AlterField(
            model_name="price",
            name="approved",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=2),
        ),
    ]
