# Generated by Django 4.1.5 on 2023-02-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapps', '0003_alter_entry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
