# Generated by Django 4.1.5 on 2023-02-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catsapps", "0002_behavor_kind_alter_cat_options_remove_cat_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="behavor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catsapps.behavor",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cat",
            name="kind",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catsapps.kind",
            ),
            preserve_default=False,
        ),
    ]
