# Generated by Django 4.1.5 on 2023-02-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breed", models.CharField(max_length=40, unique=True)),
                ("temperament", models.CharField(max_length=40, unique=True)),
                ("color", models.CharField(max_length=20, unique=True)),
                ("age", models.CharField(max_length=2, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
