# Generated by Django 4.1.5 on 2023-02-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="color",
            field=models.CharField(max_length=20),
        ),
    ]
