# Generated by Django 4.1.5 on 2023-02-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0005_alter_price_age_alter_price_breed_alter_price_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("cover", models.ImageField(upload_to="images/")),
                ("book", models.FileField(upload_to="books/")),
            ],
        ),
    ]
