# Generated by Django 4.1.5 on 2023-02-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0017_rename_resue_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(max_length=255, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
