# Generated by Django 4.1.5 on 2023-02-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0018_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="Imge",
        ),
    ]
