# Generated by Django 4.1.5 on 2023-02-11 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0019_rename_image_imge"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Imge",
            new_name="Image",
        ),
    ]
