# Generated by Django 4.1.5 on 2023-02-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0022_image_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breed", models.CharField(max_length=40)),
                ("temperament", models.CharField(max_length=40)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="price",
            name="temperament",
        ),
        migrations.AlterField(
            model_name="price",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Cats.breed"
            ),
        ),
    ]
