# Generated by Django 4.1.5 on 2023-02-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0033_remove_price_image_remove_price_imgaee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(max_length=255, null=True, upload_to="Cats/"),
        ),
    ]
