# Generated by Django 4.1.5 on 2023-02-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0038_price_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="file",
        ),
        migrations.RemoveField(
            model_name="price",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
