# Generated by Django 4.1.5 on 2023-02-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0039_remove_price_file_remove_price_image_image_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
