# Generated by Django 4.1.5 on 2023-02-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cats", "0048_alter_price_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Видимость записи"),
        ),
    ]
